### PR TITLE
last merge before deploy?

### PR DESCRIPTION
**Pull request by abraxasrex**

### CODE REVIEW

**Comment by benflinn** [comment]
We should get a new api key, and then keep the old one in the .gitignore
folder, to keep it secure. More info about it here:

https://www.reddit.com/r/webdev/comments/3nn7ei/i_think_im_ready_to_start_applying_for_jobs_hows/cvpmzvd

**Comment by abraxasrex** [comment]
okey dokey! i knew we'd have to get rid of that eventually but i forgot about it. do you wanna handle that or me? let's get merged, then you can send me a pull request so's i can deploy.

**Comment by benflinn** [comment]
yeah if you could go ahead and fix that, that'd be great.

**Comment by abraxasrex** [comment]
reading up on gitignore now; any reason we particularly need a new key though? just in case the old one was compromised?

**Comment by benflinn** [comment]
Well, someone else could just copy the key and use it... Most people are
unlikely to do that, (an API key isn't as bad as cases like this:
https://www.humankode.com/security/how-a-bug-in-visual-studio-2015-exposed-my-source-code-on-github-and-cost-me-6500-in-a-few-hours),
but it'd only take a few minutes to get a new key, make sure the old one
doesn't work anymore, and either grab the key from the server, or put it in
a .gitignore file.

Anyone can access the old key by looking at the history, so it's best to
get a new key.

It'd just be a good idea to show that we have some level of security
awareness, when we use this in our portfolios.

If you want to just copy and paste the new key in an email to me, I can
take care of it?

Ben

**Comment by abraxasrex** [comment]
That make sense. I can easily get a new key, I just don't know we'll keep it from being visible in the nightlife.js file? I suppose we could find a way to make our repo private?

**Comment by benflinn** [comment]
"Put credentials like those in an environment settings file and be sure to
add that environment settings to .gitignore. OR, define them as environment
variables in your webserver, and use getenv()
http://php.net/manual/en/function.getenv.php to access them."

https://www.reddit.com/r/webdev/comments/3nn7ei/i_think_im_ready_to_start_applying_for_jobs_hows/cvpmzvd

**Comment by abraxasrex** [comment]
here's the old and new client secret, attached . i'll figure out the
security thing tomorrow; we can't use the above strategy since we are not
using php, there's probably a similar thing for node.js tho!  I will not
rest until the app is ready and deployed tomorrow though. Sorry I've been
in and out, lots of family stuff and other projects going on.

On Sat, Oct 10, 2015 at 11:47 PM, Ben notifications@github.com wrote:

> "Put credentials like those in an environment settings file and be sure to
> add that environment settings to .gitignore. OR, define them as environment
> variables in your webserver, and use getenv()
> http://php.net/manual/en/function.getenv.php to access them."
> 
> https://www.reddit.com/r/webdev/comments/3nn7ei/i_think_im_ready_to_start_applying_for_jobs_hows/cvpmzvd
> 
> On Sat, Oct 10, 2015 at 11:18 PM, Jonathan Reasor <
> notifications@github.com>
> wrote:
> 
> > That make sense. I can easily get a new key, I just don't know we'll keep
> > it from being visible in the nightlife.js file? I suppose we could find a
> > way to make our repo private?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/benflinn/nightlife-app/pull/12#issuecomment-147152749>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/benflinn/nightlife-app/pull/12#issuecomment-147155818
> .

former:

client id:   A5UA3LYLAL1V0EZ1EPAVSP5M2RV2GKWIE05VOIB2PSN2Z0KT

client secret:  FTIBM0VRK3VTH22HZG5DUDTVZR13N3FI05Z1VFNN25PM3LXU

our app account: https://foursquare.com/developers/app/A5UA3LYLAL1V0EZ1EPAVSP5M2RV2GKWIE05VOIB2PSN2Z0KT

latter:

 client id: A5UA3LYLAL1V0EZ1EPAVSP5M2RV2GKWIE05VOIB2PSN2Z0KT

 client secret: V0K3TTWFMEVVISI5NQJN3F1MFU4GKEPPXIFSS5BHY2LQIESB

 app account: same

**Comment by abraxasrex** [comment]
this environment variables stuff is a real trip. I've had to make two stackoverflow posts in the last 12 hours.

**Comment by benflinn** [comment]
sorry to hear that :(

we're not in a huge rush, i'm just working on MEAN stuff now.

Do you have a list of the steps you're working on?

I'm happy to figure out the API security thing if you want - then you can
deploy it. Just let me know!

Ben

**Comment by abraxasrex** [comment]
My main problem is this: http://stackoverflow.com/questions/33070262/meteor-with-dotenv-package-for-environment-variables-process-is-not-defined

As for most things, there's a Meteor package for secret environment variables, as well as a Meteor.Settings solution. But I keep getting this "process is not defined" error for any of these solutions. And googling's not fixing it. If you could make a post somewhere as well and get some input from an expert, that'd be great. I'm going to start applying to positions tomorrow, though, so I really need to get this app bumped out ASAP.

**Comment by abraxasrex** [comment]
There's also this method cited in the response to my first question, which I'm still trying as well: http://stackoverflow.com/questions/33062408/the-concepts-of-git-ignore-and-not-commiting-but-still-using-global-variables

**Comment by benflinn** [comment]
The package installed properly right?

I'll play around with it for a bit tonight and see if I can make it work.

**Comment by benflinn** [comment]
figured out how to print process.env file to the server console?

i'll work on this more tomorrow - i think i can figure it out

**Comment by abraxasrex** [comment]
weird, someone responded to my second question with the exact same response as the last question. is it a dummy account or is he just playing with me?

**Comment by benflinn** [comment]
I'm having trouble narrowing it down... Any leads so far?

I was able to print process.env on the server side, using
console.log(process.env). Still have no idea how to add something from a
.env file to it though? But I know the code has to be on the server side...

**Comment by benflinn** [comment]
bots?

**Comment by abraxasrex** [comment]
I wasn't able to get it to print, so you're ahead of me. I'm trying a different method atm http://themeteorchef.com/snippets/making-use-of-settings-json/

let's just see who wins. 

so, from what I read in the dotenv doc, you're just supposed to put a .env file in the project root folder, put the keys in there like so CLIENT_ID=SOMEIDSOMETHING  and you can get it from the server using process.env.CLIENT_ID. then you could use meteor methods to get it to the client, but I couldn't get it working so I didn't get that far

**Comment by abraxasrex** [comment]
oh i was mistaken about the bots thing. just frazzled.

**Comment by abraxasrex** [comment]
HOLY CRAP IT WORKED

**Comment by abraxasrex** [comment]
I win.

**Comment by abraxasrex** [comment]
well, now i have to figure out how to ignore the file on checkout

**Comment by benflinn** [comment]
how'd you do it??? ...... haha i concede defeat..... :)

**Comment by abraxasrex** [comment]
ok, so the request is good to be pulled now, but I'm not sure if it'll pull the ignored file. If you merge everything and don't see a new file in server.js folder named settings.json, make that file and put inside it: {
"public":{
"CLIENT_ID": "our id",
"CLIENT_SECRET": "our secret"
}
}

**Comment by benflinn** [comment]
lol nice... so what was going wrong before for you? just didn't have it on
the server side?

**Comment by abraxasrex** [comment]
then when you run meteor run it with a flag like this: meteor run --settings server/settings.json

in the meteor folder, there is a text whose title might come up as blank, but at least in the text editor header you can see that it's meteor's ".gitignore" file. in that should be two entries: local, and settings.json. those file names are not tracked with git

**Comment by abraxasrex** [comment]
I just didn't use the dotenv process. this may make heroku upload more complicated, but, like at least it works

**Comment by abraxasrex** [comment]
so merge it and send me the last pull request and i'll try to get it up on heroku asap

**Comment by abraxasrex** [comment]
oh, and what do you think about changing the app name to niteplanr? i think it sounds more hip. i don't care too much either way though

**Comment by benflinn** [comment]
is this conversation in our repo? the keys are in it lol..... >< eh don't
worry about it

**Comment by benflinn** [comment]
niteplanr sounds awesome! haha

**Comment by abraxasrex** [comment]
i think this convo is only on github's servers

**Comment by abraxasrex** [comment]
on my last commit i might have forgotten one added file. completely updated as of now.

**Comment by benflinn** [comment]
i tried to merge it earlier, too many differences.. ill try again in a bit.

maybe i should just take yours,and change a couple lines? i'm still not yet
good at github...

**Comment by abraxasrex** [comment]
just manually do the major differences i guess? shouldn't take too long. my last merge from your additions had one or two conflicts i just fixed manually

**Comment by abraxasrex** [comment]
I could just deploy it as it is, and when you figure out how to merge we'll just update it

**Comment by benflinn** [comment]
k give me ten minutes to look at it quick

**Comment by benflinn** [comment]
actually, go ahead and deploy it, and then if there's any changes that need
to happen i'll let you know

**Comment by abraxasrex** [comment]
here's our url: https://nite-planr.herokuapp.com/
don't have it quite working yet, going out to dinner.

**Comment by benflinn** [comment]
awesome - looking forward to seeing it working. when it's up I will look at
the code and check to see if I had anything better (I think I was just
fixing some layout issues? Or maybe I fixed that in an earlier branch?)

**Comment by abraxasrex** [comment]
Ok you can SEE it now; toooons of issues that were easily solved when I just reinstalled heroku. lol. now to add settings and everything's gold.

**Comment by benflinn** [comment]
awesome. not working in my browser yet? keep me updated!

**Comment by abraxasrex** [comment]
I've tried 3 buildpacks now trying to get it to recognize the meteor settings. as of last build it crashed, but supposedly this last build was successful. it's just eternally loading though?

**Comment by benflinn** [comment]
hmm interesting. really don't have any experience in heroku so I can't help
much. what exactly failed about the build?

**Comment by abraxasrex** [comment]
it's saying the json isnt valid. i'll probably post another question soon. i'm 99.9% certain my syntax is okay. it knows there's stuff in the file and knows it's json, because the error logs spit the contents back at me

**Comment by abraxasrex** [comment]
so it could be heroku syntax, or json syntax, or some weird mis-install thing....sigh.

**Comment by benflinn** [comment]
you could run it through http://jshint.com/ ?

**Comment by abraxasrex** [comment]
well, I suspect it's heroku because it's the same json i ran on my local machine earlier and it worked just 
fine. just some random weirdness with heroku. may have to wait till the morning to get help and deploy. sigh.

**Comment by abraxasrex** [comment]
https://github.com/jordansissel/heroku-buildpack-meteor  this is the buildpack i've actually had success with

**Comment by tselaty** [comment]
1. All the credentials and keys you posted are not only visible to everyone/the public, but it's also forever archived. I'd recommend reissuing a new set of keys and sharing them internally over email.
2. You have some credentials/keys listed right in the repo description. Most repo's use the description area to describe the repo and how to use it/install it. It could be beneficial to do the same. Possibly a 5-step instruction to getting it working on your local system.

**Comment by abraxasrex** [comment]
Thanks for the info.  However; I removed the (old) keys from my readme.md, I do believe?

**Comment by tselaty** [comment]
Seems to still be there.

**Comment by abraxasrex** [comment]
screenshot 100

**Comment by tselaty** [comment]
https://s3.amazonaws.com/f.cl.ly/items/2m1s3e0p1U152G1i3g2B/Image%202015-10-13%20at%203.06.16%20PM.png 
image 2015-10-13 at 3 06 16 pm

You're on the nightlife-app-1 branch/fork whereas the main branch is nightlife-app, which is what I'm refering to (and also what we're commenting on).

**Comment by abraxasrex** [comment]
Ah, I see. Ben'll have to fix it, then.

**Comment by benflinn** [comment]
k, i'm going to try to resolve the conflicts... hope this works

**Pull request closed without merging**
